version: 2.{build}.0
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2017
build_script:
- ps: >-
    Write-Host $env:APPVEYOR_BUILD_VERSION
    
    Write-Host $env:APPVEYOR_PULL_REQUEST_NUMBER
    
    Write-Host $env:APPVEYOR_PULL_REQUEST_TITLE
    
    Write-Host $env:APPVEYOR_REPO_NAME
    
    Write-Host $env:APPVEYOR_REPO_BRANCH
    
    Write-Host $env:APPVEYOR_REPO_COMMIT
    
    Write-Host $env:APPVEYOR_JOB_ID

    $semver = $env:APPVEYOR_BUILD_VERSION;
    
    if($env:APPVEYOR_PULL_REQUEST_NUMBER -ge 0) {
      $semver = "$semver-PR$env:APPVEYOR_PULL_REQUEST_NUMBER";
    }

    dotnet restore

    dotnet build -c=Release /p:Version=$semver
    
    dotnet test .\HdrHistogram.UnitTests\HdrHistogram.UnitTests.csproj --no-build /p:Configuration=Release

    dotnet pack .\HdrHistogram\HdrHistogram.csproj -c=Release --no-build --include-symbols /p:Version=$semver
test: off
artifacts:
- path: .\HdrHistogram\bin\Release\*.nupkg
notifications:
- provider: GitHubPullRequest
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true